version: '3.8'

services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    volumes:
      - ./:/app
    restart: unless-stopped
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
